[2022-01-19 11:42:05,963] {processor.py:163} INFO - Started process (PID=243) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:42:05,985] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:42:05,995] {logging_mixin.py:109} INFO - [2022-01-19 11:42:05,994] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:42:06,243] {logging_mixin.py:109} INFO - [2022-01-19 11:42:06,231] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:42:06,298] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:42:06,355] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.414 seconds
[2022-01-19 11:45:31,526] {processor.py:163} INFO - Started process (PID=720) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:45:31,531] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:45:31,535] {logging_mixin.py:109} INFO - [2022-01-19 11:45:31,534] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:45:31,635] {logging_mixin.py:109} INFO - [2022-01-19 11:45:31,625] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:45:31,665] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:45:31,690] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.171 seconds
[2022-01-19 11:46:01,866] {processor.py:163} INFO - Started process (PID=842) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:46:01,870] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:46:01,873] {logging_mixin.py:109} INFO - [2022-01-19 11:46:01,873] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:46:01,939] {logging_mixin.py:109} INFO - [2022-01-19 11:46:01,932] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:46:01,954] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:46:01,970] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.110 seconds
[2022-01-19 11:46:32,856] {processor.py:163} INFO - Started process (PID=988) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:46:32,860] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:46:32,865] {logging_mixin.py:109} INFO - [2022-01-19 11:46:32,864] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:46:32,948] {logging_mixin.py:109} INFO - [2022-01-19 11:46:32,941] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:46:32,964] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:46:32,983] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.135 seconds
[2022-01-19 11:47:03,631] {processor.py:163} INFO - Started process (PID=1114) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:47:03,636] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:47:03,640] {logging_mixin.py:109} INFO - [2022-01-19 11:47:03,639] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:47:03,711] {logging_mixin.py:109} INFO - [2022-01-19 11:47:03,704] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:47:03,725] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:47:03,742] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.118 seconds
[2022-01-19 11:47:35,180] {processor.py:163} INFO - Started process (PID=1258) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:47:35,185] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:47:35,188] {logging_mixin.py:109} INFO - [2022-01-19 11:47:35,188] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:47:35,256] {logging_mixin.py:109} INFO - [2022-01-19 11:47:35,249] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:47:35,272] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:47:35,291] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.118 seconds
[2022-01-19 11:48:05,551] {processor.py:163} INFO - Started process (PID=1374) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:48:05,555] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:48:05,558] {logging_mixin.py:109} INFO - [2022-01-19 11:48:05,558] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:48:05,627] {logging_mixin.py:109} INFO - [2022-01-19 11:48:05,618] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:48:05,645] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:48:05,664] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.122 seconds
[2022-01-19 11:48:36,222] {processor.py:163} INFO - Started process (PID=1514) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:48:36,227] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:48:36,230] {logging_mixin.py:109} INFO - [2022-01-19 11:48:36,230] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:48:36,306] {logging_mixin.py:109} INFO - [2022-01-19 11:48:36,299] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:48:36,321] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:48:36,339] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.126 seconds
[2022-01-19 11:49:06,956] {processor.py:163} INFO - Started process (PID=1650) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:49:06,961] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:49:06,964] {logging_mixin.py:109} INFO - [2022-01-19 11:49:06,963] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:49:07,043] {logging_mixin.py:109} INFO - [2022-01-19 11:49:07,035] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:49:07,061] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:49:07,087] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.141 seconds
[2022-01-19 11:49:37,163] {processor.py:163} INFO - Started process (PID=1784) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:49:37,167] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:49:37,170] {logging_mixin.py:109} INFO - [2022-01-19 11:49:37,170] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:49:37,246] {logging_mixin.py:109} INFO - [2022-01-19 11:49:37,237] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:49:37,269] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:49:37,317] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.164 seconds
[2022-01-19 11:50:08,432] {processor.py:163} INFO - Started process (PID=1929) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:50:08,444] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:50:08,448] {logging_mixin.py:109} INFO - [2022-01-19 11:50:08,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:50:08,532] {logging_mixin.py:109} INFO - [2022-01-19 11:50:08,523] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:50:08,550] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:50:08,571] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.154 seconds
[2022-01-19 11:50:41,632] {processor.py:163} INFO - Started process (PID=2053) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:50:41,637] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:50:41,644] {logging_mixin.py:109} INFO - [2022-01-19 11:50:41,643] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:50:41,733] {logging_mixin.py:109} INFO - [2022-01-19 11:50:41,724] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:50:41,752] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:50:41,779] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.156 seconds
[2022-01-19 11:54:20,464] {processor.py:163} INFO - Started process (PID=179) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:54:20,501] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:54:20,505] {logging_mixin.py:109} INFO - [2022-01-19 11:54:20,504] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:54:20,708] {logging_mixin.py:109} INFO - [2022-01-19 11:54:20,697] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:54:20,762] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:54:20,819] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.362 seconds
[2022-01-19 11:55:02,976] {processor.py:163} INFO - Started process (PID=323) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:55:02,986] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:55:02,993] {logging_mixin.py:109} INFO - [2022-01-19 11:55:02,992] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:55:03,158] {logging_mixin.py:109} INFO - [2022-01-19 11:55:03,148] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:55:03,197] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:55:03,230] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.266 seconds
[2022-01-19 11:55:33,363] {processor.py:163} INFO - Started process (PID=449) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:55:33,367] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:55:33,371] {logging_mixin.py:109} INFO - [2022-01-19 11:55:33,370] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:55:33,437] {logging_mixin.py:109} INFO - [2022-01-19 11:55:33,430] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:55:33,452] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:55:33,471] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.115 seconds
[2022-01-19 11:56:04,077] {processor.py:163} INFO - Started process (PID=596) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:56:04,082] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:56:04,086] {logging_mixin.py:109} INFO - [2022-01-19 11:56:04,086] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:56:04,168] {logging_mixin.py:109} INFO - [2022-01-19 11:56:04,159] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:56:04,190] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:56:04,214] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.145 seconds
[2022-01-19 11:56:34,414] {processor.py:163} INFO - Started process (PID=720) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:56:34,418] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:56:34,420] {logging_mixin.py:109} INFO - [2022-01-19 11:56:34,420] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:56:34,481] {logging_mixin.py:109} INFO - [2022-01-19 11:56:34,475] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:56:34,494] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:56:34,520] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.113 seconds
[2022-01-19 11:57:04,938] {processor.py:163} INFO - Started process (PID=866) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:57:04,942] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:57:04,945] {logging_mixin.py:109} INFO - [2022-01-19 11:57:04,945] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:57:05,014] {logging_mixin.py:109} INFO - [2022-01-19 11:57:05,007] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:57:05,030] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:57:05,048] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.117 seconds
[2022-01-19 11:57:35,457] {processor.py:163} INFO - Started process (PID=993) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:57:35,462] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:57:35,465] {logging_mixin.py:109} INFO - [2022-01-19 11:57:35,464] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:57:35,526] {logging_mixin.py:109} INFO - [2022-01-19 11:57:35,519] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:57:35,539] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:57:35,554] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.103 seconds
[2022-01-19 11:58:06,311] {processor.py:163} INFO - Started process (PID=1135) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:58:06,315] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:58:06,318] {logging_mixin.py:109} INFO - [2022-01-19 11:58:06,317] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:58:06,388] {logging_mixin.py:109} INFO - [2022-01-19 11:58:06,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:58:06,405] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:58:06,426] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.134 seconds
[2022-01-19 11:58:18,404] {processor.py:163} INFO - Started process (PID=1171) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:58:18,408] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 11:58:18,412] {logging_mixin.py:109} INFO - [2022-01-19 11:58:18,412] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:58:18,488] {logging_mixin.py:109} INFO - [2022-01-19 11:58:18,479] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 11:58:18,504] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 11:58:18,539] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.143 seconds
[2022-01-19 12:04:18,266] {processor.py:163} INFO - Started process (PID=2480) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:04:18,270] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:04:18,276] {logging_mixin.py:109} INFO - [2022-01-19 12:04:18,274] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:04:18,370] {logging_mixin.py:109} INFO - [2022-01-19 12:04:18,363] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:04:18,385] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:04:18,406] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.147 seconds
[2022-01-19 12:04:48,544] {processor.py:163} INFO - Started process (PID=2605) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:04:48,549] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:04:48,552] {logging_mixin.py:109} INFO - [2022-01-19 12:04:48,552] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:04:48,627] {logging_mixin.py:109} INFO - [2022-01-19 12:04:48,619] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:04:48,641] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:04:48,658] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.122 seconds
[2022-01-19 12:05:19,480] {processor.py:163} INFO - Started process (PID=2742) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:05:19,488] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:05:19,493] {logging_mixin.py:109} INFO - [2022-01-19 12:05:19,492] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:05:19,569] {logging_mixin.py:109} INFO - [2022-01-19 12:05:19,562] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:05:19,586] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:05:19,606] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.133 seconds
[2022-01-19 12:05:49,869] {processor.py:163} INFO - Started process (PID=2864) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:05:49,874] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:05:49,877] {logging_mixin.py:109} INFO - [2022-01-19 12:05:49,877] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:05:49,946] {logging_mixin.py:109} INFO - [2022-01-19 12:05:49,939] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:05:49,960] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:05:49,977] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.116 seconds
[2022-01-19 12:06:20,524] {processor.py:163} INFO - Started process (PID=3002) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:06:20,529] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:06:20,532] {logging_mixin.py:109} INFO - [2022-01-19 12:06:20,532] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:06:20,605] {logging_mixin.py:109} INFO - [2022-01-19 12:06:20,596] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:06:20,620] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:06:20,640] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.123 seconds
[2022-01-19 12:06:50,904] {processor.py:163} INFO - Started process (PID=3123) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:06:50,908] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:06:50,911] {logging_mixin.py:109} INFO - [2022-01-19 12:06:50,911] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:06:50,981] {logging_mixin.py:109} INFO - [2022-01-19 12:06:50,974] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:06:50,996] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:06:51,015] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.117 seconds
[2022-01-19 12:07:21,573] {processor.py:163} INFO - Started process (PID=3261) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:07:21,594] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:07:21,601] {logging_mixin.py:109} INFO - [2022-01-19 12:07:21,600] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:07:21,723] {logging_mixin.py:109} INFO - [2022-01-19 12:07:21,714] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:07:21,751] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:07:21,778] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.212 seconds
[2022-01-19 12:07:52,286] {processor.py:163} INFO - Started process (PID=3382) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:07:52,291] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:07:52,294] {logging_mixin.py:109} INFO - [2022-01-19 12:07:52,293] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:07:52,363] {logging_mixin.py:109} INFO - [2022-01-19 12:07:52,356] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:07:52,379] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:07:52,398] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.118 seconds
[2022-01-19 12:08:23,834] {processor.py:163} INFO - Started process (PID=3519) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:08:23,838] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:08:23,843] {logging_mixin.py:109} INFO - [2022-01-19 12:08:23,842] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:08:23,918] {logging_mixin.py:109} INFO - [2022-01-19 12:08:23,912] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/NameGenderCSVtoRedshift_v4.py", line 70, in <module>
    'url':  Variable.get("csv_url")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable csv_url does not exist'
[2022-01-19 12:08:23,946] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:08:23,978] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.153 seconds
[2022-01-19 12:09:59,957] {processor.py:163} INFO - Started process (PID=3831) to work on /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:09:59,962] {processor.py:620} INFO - Processing file /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py for tasks to queue
[2022-01-19 12:09:59,965] {logging_mixin.py:109} INFO - [2022-01-19 12:09:59,965] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:10:00,000] {processor.py:634} WARNING - No viable dags retrieved from /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py
[2022-01-19 12:10:00,003] {processor.py:171} INFO - Processing /opt/airflow/dags/NameGenderCSVtoRedshift_v4.py took 0.055 seconds
