{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2fca2479-e0cb-45e8-b34c-adfce5617fd7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "id": "20703226-859a-4132-b33c-a87a1a975288",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: done\n",
      "\n",
      "# All requested packages already installed.\n",
      "\n",
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: done\n",
      "\n",
      "# All requested packages already installed.\n",
      "\n",
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: done\n",
      "\n",
      "# All requested packages already installed.\n",
      "\n",
      "Collecting package metadata (current_repodata.json): done\n",
      "Solving environment: done\n",
      "\n",
      "## Package Plan ##\n",
      "\n",
      "  environment location: /opt/homebrew/anaconda3/envs/studyETL\n",
      "\n",
      "  added / updated specs:\n",
      "    - ipython-sql\n",
      "\n",
      "\n",
      "The following packages will be downloaded:\n",
      "\n",
      "    package                    |            build\n",
      "    ---------------------------|-----------------\n",
      "    importlib-metadata-4.10.1  |   py39h6e9494a_0          33 KB  conda-forge\n",
      "    ipython-sql-0.3.9          |  pyhd8ed1ab_1004          18 KB  conda-forge\n",
      "    ipython_genutils-0.2.0     |             py_1          21 KB  conda-forge\n",
      "    prettytable-3.0.0          |     pyhd8ed1ab_0          25 KB  conda-forge\n",
      "    sqlparse-0.4.2             |     pyhd8ed1ab_0          34 KB  conda-forge\n",
      "    zipp-3.7.0                 |     pyhd8ed1ab_0          12 KB  conda-forge\n",
      "    ------------------------------------------------------------\n",
      "                                           Total:         142 KB\n",
      "\n",
      "The following NEW packages will be INSTALLED:\n",
      "\n",
      "  importlib-metadata conda-forge/osx-64::importlib-metadata-4.10.1-py39h6e9494a_0\n",
      "  ipython-sql        conda-forge/noarch::ipython-sql-0.3.9-pyhd8ed1ab_1004\n",
      "  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1\n",
      "  prettytable        conda-forge/noarch::prettytable-3.0.0-pyhd8ed1ab_0\n",
      "  sqlparse           conda-forge/noarch::sqlparse-0.4.2-pyhd8ed1ab_0\n",
      "  zipp               conda-forge/noarch::zipp-3.7.0-pyhd8ed1ab_0\n",
      "\n",
      "\n",
      "\n",
      "Downloading and Extracting Packages\n",
      "sqlparse-0.4.2       | 34 KB     | ##################################### | 100% \n",
      "ipython-sql-0.3.9    | 18 KB     | ##################################### | 100% \n",
      "importlib-metadata-4 | 33 KB     | ##################################### | 100% \n",
      "zipp-3.7.0           | 12 KB     | ##################################### | 100% \n",
      "prettytable-3.0.0    | 25 KB     | ##################################### | 100% \n",
      "ipython_genutils-0.2 | 21 KB     | ##################################### | 100% \n",
      "Preparing transaction: done\n",
      "Verifying transaction: - WARNING conda.core.path_actions:verify(962): Unable to create environments file. Path not writable.\n",
      "  environment location: /Users/mdgome/.conda/environments.txt\n",
      "\n",
      "done\n",
      "Executing transaction: / WARNING conda.core.envs_manager:register_env(50): Unable to register environment. Path not writable or missing.\n",
      "  environment location: /opt/homebrew/anaconda3/envs/studyETL\n",
      "  registry file: /Users/mdgome/.conda/environments.txt\n",
      "done\n"
     ]
    }
   ],
   "source": [
    "!conda install -c conda-forge -y --prefix {sys.prefix} pandas\n",
    "!conda install -c conda-forge -y --prefix {sys.prefix} sqlalchemy\n",
    "!conda install -c conda-forge -y --prefix {sys.prefix} pymysql\n",
    "!conda install -c conda-forge -y --prefix {sys.prefix} ipython-sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 109,
   "id": "89ca485c-5520-42a1-a99c-6f0a5ceae560",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import general package\n",
    "from datetime import datetime\n",
    "import logging\n",
    "import sys\n",
    "# import Transform\n",
    "import pandas as pd\n",
    "# import mysql.connector\n",
    "from sqlalchemy import create_engine\n",
    "import pymysql\n",
    "# import airflow package\n",
    "#from airflow import DAG\n",
    "#from airflow.operators.python import PythonOperator"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 127,
   "id": "70697ebc-5e9f-4753-acda-52e9a4a7c329",
   "metadata": {},
   "outputs": [],
   "source": [
    "def _get_MySQL_Connection():\n",
    "    from mydb_credentials import aws_mysql_ec2_study\n",
    "    connection_string = aws_mysql_ec2_study()\n",
    "    engine = create_engine(connection_string, encoding=encoding)\n",
    "    try:\n",
    "        conn = engine.raw_connection()\n",
    "        logging.info('DB Connect : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )\n",
    "        return conn.cursor(pymysql.cursors.DictCurosr)\n",
    "    except Exception as e:\n",
    "        logging.error('DB Connect Error : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )\n",
    "        logging.error(e.message)\n",
    "        sys.exit(5)\n",
    "#        session.rollback()\n",
    "    #connection_string"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 128,
   "id": "e27c6d88-7616-4feb-b6c9-1b849cb7df24",
   "metadata": {},
   "outputs": [],
   "source": [
    "def DataToCSV(df):\n",
    "    now_date = datetime.now().strftime('%Y.%m.%d.%H.%M')\n",
    "    file_name = now_date+\"output.csv\"\n",
    "    df.to_csv(file_name,index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "030f778b",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'mysql+pymysql://mdgome:Rlawjdals1!@ec2-15-164-164-229.ap-northeast-2.compute.amazonaws.com:3306/airflow?utf8'"
      ]
     },
     "execution_count": 41,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "engineString = connect_mysql()\n",
    "engineString"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 130,
   "id": "f8d8f630-5834-4c24-872f-1bf7482c2212",
   "metadata": {},
   "outputs": [],
   "source": [
    "def etl():\n",
    "    df = load()\n",
    "    DataToCSV(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 131,
   "id": "447052b8-11cc-4d11-878b-a53ade81708b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"/var/folders/0j/gzlqhwtn7gg81y1sxjmmbv8m0000gn/T/ipykernel_15501/2703032269.py\", line 8, in _get_MySQL_Connection\n",
      "    return conn.cursor(pymysql.cursors.DictCurosr)\n",
      "AttributeError: module 'pymysql.cursors' has no attribute 'DictCurosr'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/logging/__init__.py\", line 1083, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/logging/__init__.py\", line 927, in format\n",
      "    return fmt.format(record)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/logging/__init__.py\", line 663, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/logging/__init__.py\", line 367, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "    return _run_code(code, main_globals, None,\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/runpy.py\", line 87, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/traitlets/config/application.py\", line 846, in launch_instance\n",
      "    app.start()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/kernelapp.py\", line 677, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/asyncio/base_events.py\", line 596, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/asyncio/base_events.py\", line 1890, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/asyncio/events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 461, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 450, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 357, in dispatch_shell\n",
      "    await result\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/kernelbase.py\", line 652, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2768, in run_cell\n",
      "    # If the call was made with 0 or None exit status (sys.exit(0)\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 2814, in _run_cell\n",
      "    # Find things also in current directory.  This is needed to mimic the\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3012, in run_cell_async\n",
      "    ----------\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3191, in run_ast_nodes\n",
      "    def transform_cell(self, raw_cell):\n",
      "  File \"/opt/homebrew/anaconda3/envs/studyETL/lib/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3251, in run_code\n",
      "  File \"/var/folders/0j/gzlqhwtn7gg81y1sxjmmbv8m0000gn/T/ipykernel_15501/1037478285.py\", line 1, in <module>\n",
      "    etl()\n",
      "  File \"/var/folders/0j/gzlqhwtn7gg81y1sxjmmbv8m0000gn/T/ipykernel_15501/3128401565.py\", line 2, in etl\n",
      "    df = load()\n",
      "  File \"/var/folders/0j/gzlqhwtn7gg81y1sxjmmbv8m0000gn/T/ipykernel_15501/2880225984.py\", line 2, in load\n",
      "    cur = _get_MySQL_Connection()\n",
      "  File \"/var/folders/0j/gzlqhwtn7gg81y1sxjmmbv8m0000gn/T/ipykernel_15501/2703032269.py\", line 10, in _get_MySQL_Connection\n",
      "    logging.error('DB Connect Error : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )\n",
      "Message: 'DB Connect Error : '\n",
      "Arguments: ('2022.01.19.14.54',)\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'AttributeError' object has no attribute 'message'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Input \u001b[0;32mIn [127]\u001b[0m, in \u001b[0;36m_get_MySQL_Connection\u001b[0;34m()\u001b[0m\n\u001b[1;32m      7\u001b[0m     logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mDB Connect : \u001b[39m\u001b[38;5;124m'\u001b[39m,datetime\u001b[38;5;241m.\u001b[39mnow()\u001b[38;5;241m.\u001b[39mstrftime(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mY.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mm.\u001b[39m\u001b[38;5;132;01m%d\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mH.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mM\u001b[39m\u001b[38;5;124m'\u001b[39m) )\n\u001b[0;32m----> 8\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m conn\u001b[38;5;241m.\u001b[39mcursor(\u001b[43mpymysql\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcursors\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mDictCurosr\u001b[49m)\n\u001b[1;32m      9\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "\u001b[0;31mAttributeError\u001b[0m: module 'pymysql.cursors' has no attribute 'DictCurosr'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Input \u001b[0;32mIn [131]\u001b[0m, in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43metl\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "Input \u001b[0;32mIn [130]\u001b[0m, in \u001b[0;36metl\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21metl\u001b[39m():\n\u001b[0;32m----> 2\u001b[0m     df \u001b[38;5;241m=\u001b[39m \u001b[43mload\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      3\u001b[0m     DataToCSV(df)\n",
      "Input \u001b[0;32mIn [129]\u001b[0m, in \u001b[0;36mload\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mload\u001b[39m():\n\u001b[0;32m----> 2\u001b[0m     cur \u001b[38;5;241m=\u001b[39m \u001b[43m_get_MySQL_Connection\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      3\u001b[0m     sql \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mselect user,email from member;\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m      4\u001b[0m     cur\u001b[38;5;241m.\u001b[39mexecute(sql)\n",
      "Input \u001b[0;32mIn [127]\u001b[0m, in \u001b[0;36m_get_MySQL_Connection\u001b[0;34m()\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     10\u001b[0m     logging\u001b[38;5;241m.\u001b[39merror(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mDB Connect Error : \u001b[39m\u001b[38;5;124m'\u001b[39m,datetime\u001b[38;5;241m.\u001b[39mnow()\u001b[38;5;241m.\u001b[39mstrftime(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mY.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mm.\u001b[39m\u001b[38;5;132;01m%d\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mH.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mM\u001b[39m\u001b[38;5;124m'\u001b[39m) )\n\u001b[0;32m---> 11\u001b[0m     logging\u001b[38;5;241m.\u001b[39merror(\u001b[43me\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmessage\u001b[49m)\n\u001b[1;32m     12\u001b[0m     sys\u001b[38;5;241m.\u001b[39mexit(\u001b[38;5;241m5\u001b[39m)\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'AttributeError' object has no attribute 'message'"
     ]
    }
   ],
   "source": [
    "etl()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "1c557818-6c96-4201-b21c-ce86073a1eb2",
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "'Engine' object is not callable",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Input \u001b[0;32mIn [66]\u001b[0m, in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43metl\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "Input \u001b[0;32mIn [65]\u001b[0m, in \u001b[0;36metl\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21metl\u001b[39m():\n\u001b[0;32m----> 2\u001b[0m     conn \u001b[38;5;241m=\u001b[39m \u001b[43msession\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbind\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m      6\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m: \n\u001b[1;32m      7\u001b[0m         logging\u001b[38;5;241m.\u001b[39minfo(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mDB Connect : \u001b[39m\u001b[38;5;124m'\u001b[39m,datetime\u001b[38;5;241m.\u001b[39mnow()\u001b[38;5;241m.\u001b[39mstrftime(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mY.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mm.\u001b[39m\u001b[38;5;132;01m%d\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mH.\u001b[39m\u001b[38;5;124m%\u001b[39m\u001b[38;5;124mM\u001b[39m\u001b[38;5;124m'\u001b[39m) )\n",
      "\u001b[0;31mTypeError\u001b[0m: 'Engine' object is not callable"
     ]
    }
   ],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ef343365-bea7-4a6d-8366-e2172445a3fd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "studyETL",
   "language": "python",
   "name": "studyetl"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
