[2022-01-20 03:21:04,011] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-20T00:20:00+00:00 [queued]>
[2022-01-20 03:21:04,397] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-20T00:20:00+00:00 [queued]>
[2022-01-20 03:21:04,403] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 03:21:04,405] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-20 03:21:04,406] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 03:21:04,743] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): MySQLTOCsv> on 2022-01-20 00:20:00+00:00
[2022-01-20 03:21:04,777] {standard_task_runner.py:52} INFO - Started process 332 to run task
[2022-01-20 03:21:04,808] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MySQLTOCsv', 'MySQLTOCsv', 'scheduled__2022-01-20T00:20:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py', '--cfg-path', '/tmp/tmpj_nxy8k2', '--error-file', '/tmp/tmpkf2tmmui']
[2022-01-20 03:21:04,812] {standard_task_runner.py:77} INFO - Job 28: Subtask MySQLTOCsv
[2022-01-20 03:21:05,495] {logging_mixin.py:109} INFO - Running <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-20T00:20:00+00:00 [running]> on host 2d9e08f9455b
[2022-01-20 03:21:06,804] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MySQLTOCsv
AIRFLOW_CTX_TASK_ID=MySQLTOCsv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T00:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-20T00:20:00+00:00
[2022-01-20 03:21:06,912] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-20 03:21:06,922] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-20 03:21:06,935] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-20 03:21:06,945] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-20 03:21:06,962] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-20 03:21:06,965] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-20 03:21:06,967] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-20 03:21:06,970] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-20 03:21:07,220] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-20 03:21:07,224] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-20 03:21:07,226] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,234] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,235] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-20 03:21:07,242] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-20 03:21:07,244] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-20 03:21:07,250] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-20 03:21:07,252] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-20 03:21:07,259] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-20 03:21:07,267] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-20 03:21:07,270] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-20 03:21:07,272] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-20 03:21:07,274] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-20 03:21:07,279] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-20 03:21:07,282] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-20 03:21:07,289] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-20 03:21:07,291] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-20 03:21:07,293] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-20 03:21:07,295] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-20 03:21:07,297] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-20 03:21:07,299] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-20 03:21:07,303] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-20 03:21:07,308] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-20 03:21:07,312] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-20 03:21:07,316] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-20 03:21:07,320] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-20 03:21:07,323] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-20 03:21:07,327] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-20 03:21:07,332] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-20 03:21:07,338] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-20 03:21:07,341] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-20 03:21:07,343] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-20 03:21:07,345] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-20 03:21:07,348] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-20 03:21:07,350] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-20 03:21:07,352] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-20 03:21:07,356] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,364] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,370] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:07,374] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-20 03:21:07,378] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-20 03:21:07,383] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-20 03:21:07,388] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-20 03:21:07,391] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-20 03:21:07,395] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-20 03:21:07,397] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,401] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,403] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:07,406] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-20 03:21:07,408] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-20 03:21:07,410] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-20 03:21:07,412] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-20 03:21:07,415] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-20 03:21:07,417] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-20 03:21:07,420] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-20 03:21:07,423] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-20 03:21:07,425] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 80, in etl
    df = load()
[2022-01-20 03:21:07,429] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 71, in load
    cur = _get_MySQL_Connection()
[2022-01-20 03:21:07,431] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 48, in _get_MySQL_Connection
    logging.info('DB Connect : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )
[2022-01-20 03:21:07,436] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-20 03:21:07,440] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-20 03:21:07,449] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-20 03:21:07,487] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-20 03:21:07,500] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-20 03:21:07,513] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-20 03:21:07,524] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-20 03:21:07,531] {logging_mixin.py:109} WARNING - Message: 'DB Connect : '
Arguments: ('2022.01.20.03.21',)
[2022-01-20 03:21:07,799] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-20 03:21:07,803] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-20 03:21:07,807] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-20 03:21:07,809] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-20 03:21:07,815] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-20 03:21:07,817] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-20 03:21:07,821] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-20 03:21:07,824] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-20 03:21:07,850] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-20 03:21:07,860] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-20 03:21:07,869] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,881] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,884] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-20 03:21:07,913] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-20 03:21:07,936] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-20 03:21:07,942] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-20 03:21:07,944] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-20 03:21:07,951] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-20 03:21:07,964] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-20 03:21:07,980] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-20 03:21:07,985] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-20 03:21:07,989] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-20 03:21:07,996] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-20 03:21:08,007] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-20 03:21:08,009] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-20 03:21:08,017] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-20 03:21:08,020] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-20 03:21:08,032] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-20 03:21:08,037] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-20 03:21:08,047] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-20 03:21:08,053] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-20 03:21:08,062] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-20 03:21:08,069] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-20 03:21:08,076] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-20 03:21:08,083] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-20 03:21:08,093] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-20 03:21:08,097] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-20 03:21:08,104] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-20 03:21:08,110] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-20 03:21:08,120] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-20 03:21:08,128] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-20 03:21:08,135] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-20 03:21:08,138] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-20 03:21:08,146] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-20 03:21:08,155] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-20 03:21:08,162] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:08,164] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:08,165] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:08,171] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-20 03:21:08,173] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-20 03:21:08,174] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-20 03:21:08,176] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-20 03:21:08,181] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-20 03:21:08,183] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-20 03:21:08,185] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:08,194] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:08,195] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:08,198] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-20 03:21:08,200] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-20 03:21:08,203] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-20 03:21:08,205] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-20 03:21:08,207] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-20 03:21:08,212] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-20 03:21:08,216] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-20 03:21:08,218] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-20 03:21:08,222] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 81, in etl
    DataToCSV(df)
[2022-01-20 03:21:08,226] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 69, in DataToCSV
    logging.info('File Created: ', output_file)
[2022-01-20 03:21:08,230] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-20 03:21:08,236] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-20 03:21:08,238] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-20 03:21:08,245] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-20 03:21:08,247] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-20 03:21:08,251] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-20 03:21:08,256] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-20 03:21:08,259] {logging_mixin.py:109} WARNING - Message: 'File Created: '
Arguments: ('/opt/***/data/mysqlData/2022.01.20_03.21_output.csv',)
[2022-01-20 03:21:08,268] {python.py:152} INFO - Done. Returned value was: None
[2022-01-20 03:21:08,557] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=MySQLTOCsv, task_id=MySQLTOCsv, execution_date=20220120T002000, start_date=20220120T032104, end_date=20220120T032108
[2022-01-20 03:21:08,864] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-20 03:21:09,304] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
