[2022-01-20 03:21:03,323] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-19T15:20:00+00:00 [queued]>
[2022-01-20 03:21:03,739] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-19T15:20:00+00:00 [queued]>
[2022-01-20 03:21:03,760] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 03:21:03,773] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-20 03:21:03,774] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-20 03:21:04,180] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): MySQLTOCsv> on 2022-01-19 15:20:00+00:00
[2022-01-20 03:21:04,206] {standard_task_runner.py:52} INFO - Started process 330 to run task
[2022-01-20 03:21:04,250] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MySQLTOCsv', 'MySQLTOCsv', 'scheduled__2022-01-19T15:20:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/MySQL_to_CSV.py', '--cfg-path', '/tmp/tmpavjpfqja', '--error-file', '/tmp/tmpa6mee4e3']
[2022-01-20 03:21:04,257] {standard_task_runner.py:77} INFO - Job 22: Subtask MySQLTOCsv
[2022-01-20 03:21:04,860] {logging_mixin.py:109} INFO - Running <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-19T15:20:00+00:00 [running]> on host 2d9e08f9455b
[2022-01-20 03:21:05,820] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MySQLTOCsv
AIRFLOW_CTX_TASK_ID=MySQLTOCsv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T15:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-19T15:20:00+00:00
[2022-01-20 03:21:05,909] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-20 03:21:05,914] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-20 03:21:05,916] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-20 03:21:05,917] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-20 03:21:05,922] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-20 03:21:05,924] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-20 03:21:05,927] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-20 03:21:05,929] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-20 03:21:06,331] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-20 03:21:06,339] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-20 03:21:06,342] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:06,348] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:06,353] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-20 03:21:06,358] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-20 03:21:06,366] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-20 03:21:06,373] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-20 03:21:06,375] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-20 03:21:06,379] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-20 03:21:06,386] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-20 03:21:06,390] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-20 03:21:06,402] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-20 03:21:06,407] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-20 03:21:06,410] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-20 03:21:06,412] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-20 03:21:06,415] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-20 03:21:06,419] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-20 03:21:06,423] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-20 03:21:06,429] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-20 03:21:06,435] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-20 03:21:06,437] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-20 03:21:06,446] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-20 03:21:06,449] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-20 03:21:06,455] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-20 03:21:06,457] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-20 03:21:06,461] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-20 03:21:06,464] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-20 03:21:06,469] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-20 03:21:06,476] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-20 03:21:06,483] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-20 03:21:06,487] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-20 03:21:06,496] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-20 03:21:06,500] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-20 03:21:06,507] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-20 03:21:06,512] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-20 03:21:06,519] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-20 03:21:06,530] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:06,536] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:06,542] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:06,547] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-20 03:21:06,554] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-20 03:21:06,562] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-20 03:21:06,569] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-20 03:21:06,579] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-20 03:21:06,582] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-20 03:21:06,596] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:06,600] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:06,609] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:06,614] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-20 03:21:06,618] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-20 03:21:06,624] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-20 03:21:06,632] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-20 03:21:06,637] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-20 03:21:06,644] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-20 03:21:06,650] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-20 03:21:06,666] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-20 03:21:06,673] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 80, in etl
    df = load()
[2022-01-20 03:21:06,681] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 71, in load
    cur = _get_MySQL_Connection()
[2022-01-20 03:21:06,690] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 48, in _get_MySQL_Connection
    logging.info('DB Connect : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )
[2022-01-20 03:21:06,700] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-20 03:21:06,708] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-20 03:21:06,714] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-20 03:21:06,719] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-20 03:21:06,724] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-20 03:21:06,728] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-20 03:21:06,733] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-20 03:21:06,736] {logging_mixin.py:109} WARNING - Message: 'DB Connect : '
Arguments: ('2022.01.20.03.21',)
[2022-01-20 03:21:07,170] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-20 03:21:07,177] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-20 03:21:07,190] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-20 03:21:07,201] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-20 03:21:07,206] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-20 03:21:07,212] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-20 03:21:07,217] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-20 03:21:07,224] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-20 03:21:07,252] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-20 03:21:07,275] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-20 03:21:07,278] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,282] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,290] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-20 03:21:07,294] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-20 03:21:07,295] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-20 03:21:07,300] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-20 03:21:07,303] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-20 03:21:07,305] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-20 03:21:07,308] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-20 03:21:07,318] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-20 03:21:07,320] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-20 03:21:07,321] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-20 03:21:07,323] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-20 03:21:07,325] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-20 03:21:07,327] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-20 03:21:07,329] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-20 03:21:07,332] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-20 03:21:07,333] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-20 03:21:07,339] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-20 03:21:07,342] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-20 03:21:07,346] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-20 03:21:07,351] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-20 03:21:07,355] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-20 03:21:07,364] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-20 03:21:07,369] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-20 03:21:07,372] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-20 03:21:07,375] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-20 03:21:07,379] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-20 03:21:07,381] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-20 03:21:07,385] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-20 03:21:07,390] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-20 03:21:07,392] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-20 03:21:07,395] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-20 03:21:07,399] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-20 03:21:07,401] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-20 03:21:07,403] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,406] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,408] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:07,411] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-20 03:21:07,413] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-20 03:21:07,415] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-20 03:21:07,417] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-20 03:21:07,419] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-20 03:21:07,422] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-20 03:21:07,426] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-20 03:21:07,429] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-20 03:21:07,431] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-20 03:21:07,433] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-20 03:21:07,437] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-20 03:21:07,445] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-20 03:21:07,450] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-20 03:21:07,455] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-20 03:21:07,461] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-20 03:21:07,465] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-20 03:21:07,468] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-20 03:21:07,473] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 81, in etl
    DataToCSV(df)
[2022-01-20 03:21:07,478] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 69, in DataToCSV
    logging.info('File Created: ', output_file)
[2022-01-20 03:21:07,480] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-20 03:21:07,485] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-20 03:21:07,489] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-20 03:21:07,492] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-20 03:21:07,498] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-20 03:21:07,505] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-20 03:21:07,514] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-20 03:21:07,521] {logging_mixin.py:109} WARNING - Message: 'File Created: '
Arguments: ('/opt/***/data/mysqlData/2022.01.20_03.21_output.csv',)
[2022-01-20 03:21:07,527] {python.py:152} INFO - Done. Returned value was: None
[2022-01-20 03:21:07,987] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=MySQLTOCsv, task_id=MySQLTOCsv, execution_date=20220119T152000, start_date=20220120T032103, end_date=20220120T032107
[2022-01-20 03:21:08,422] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-20 03:21:08,942] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
