[2022-01-19 14:20:03,339] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-19T13:20:00+00:00 [queued]>
[2022-01-19 14:20:03,396] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-19T13:20:00+00:00 [queued]>
[2022-01-19 14:20:03,398] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 14:20:03,400] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-19 14:20:03,402] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 14:20:03,454] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): MySQLTOCsv> on 2022-01-19 13:20:00+00:00
[2022-01-19 14:20:03,463] {standard_task_runner.py:52} INFO - Started process 7928 to run task
[2022-01-19 14:20:03,475] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MySQLTOCsv', 'MySQLTOCsv', 'scheduled__2022-01-19T13:20:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/MySQL_to_CSV.py', '--cfg-path', '/tmp/tmp355qluar', '--error-file', '/tmp/tmpyo8g8xlq']
[2022-01-19 14:20:03,478] {standard_task_runner.py:77} INFO - Job 13: Subtask MySQLTOCsv
[2022-01-19 14:20:03,682] {logging_mixin.py:109} INFO - Running <TaskInstance: MySQLTOCsv.MySQLTOCsv scheduled__2022-01-19T13:20:00+00:00 [running]> on host 2d9e08f9455b
[2022-01-19 14:20:03,869] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MySQLTOCsv
AIRFLOW_CTX_TASK_ID=MySQLTOCsv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T13:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-19T13:20:00+00:00
[2022-01-19 14:20:04,005] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-19 14:20:04,011] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-19 14:20:04,013] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-19 14:20:04,014] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-19 14:20:04,015] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-19 14:20:04,017] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-19 14:20:04,018] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-19 14:20:04,020] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-19 14:20:04,052] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-19 14:20:04,054] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-19 14:20:04,055] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:20:04,056] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:20:04,058] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-19 14:20:04,059] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-19 14:20:04,061] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-19 14:20:04,063] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-19 14:20:04,064] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-19 14:20:04,065] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-19 14:20:04,066] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-19 14:20:04,067] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-19 14:20:04,069] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-19 14:20:04,070] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-19 14:20:04,072] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-19 14:20:04,073] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-19 14:20:04,074] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-19 14:20:04,076] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-19 14:20:04,076] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-19 14:20:04,077] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-19 14:20:04,079] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-19 14:20:04,080] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-19 14:20:04,081] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-19 14:20:04,082] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-19 14:20:04,084] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-19 14:20:04,085] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-19 14:20:04,087] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-19 14:20:04,089] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-19 14:20:04,090] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-19 14:20:04,092] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-19 14:20:04,094] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-19 14:20:04,095] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-19 14:20:04,096] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-19 14:20:04,097] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-19 14:20:04,098] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-19 14:20:04,100] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-19 14:20:04,101] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-19 14:20:04,102] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:20:04,104] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:20:04,105] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:20:04,106] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-19 14:20:04,108] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-19 14:20:04,109] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-19 14:20:04,110] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-19 14:20:04,111] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-19 14:20:04,113] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-19 14:20:04,114] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:20:04,115] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:20:04,116] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:20:04,117] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-19 14:20:04,119] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-19 14:20:04,120] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-19 14:20:04,121] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-19 14:20:04,122] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-19 14:20:04,124] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-19 14:20:04,125] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-19 14:20:04,126] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-19 14:20:04,127] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 78, in etl
    df = load()
[2022-01-19 14:20:04,128] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 69, in load
    cur = _get_MySQL_Connection()
[2022-01-19 14:20:04,130] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 48, in _get_MySQL_Connection
    logging.info('DB Connect : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )
[2022-01-19 14:20:04,131] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-19 14:20:04,132] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-19 14:20:04,133] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-19 14:20:04,135] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-19 14:20:04,137] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-19 14:20:04,138] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-19 14:20:04,139] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-19 14:20:04,141] {logging_mixin.py:109} WARNING - Message: 'DB Connect : '
Arguments: ('2022.01.19.14.20',)
[2022-01-19 14:20:04,171] {taskinstance.py:1686} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/MySQL_to_CSV.py", line 79, in etl
    DataToCSV(df)
  File "/opt/airflow/dags/MySQL_to_CSV.py", line 66, in DataToCSV
    df.to_csv(mkdirPath+"/"+file_name,index=False)
NameError: name 'mkdirPath' is not defined
[2022-01-19 14:20:04,214] {taskinstance.py:1280} INFO - Marking task as FAILED. dag_id=MySQLTOCsv, task_id=MySQLTOCsv, execution_date=20220119T132000, start_date=20220119T142003, end_date=20220119T142004
[2022-01-19 14:20:04,268] {standard_task_runner.py:91} ERROR - Failed to execute job 13 for task MySQLTOCsv
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/MySQL_to_CSV.py", line 79, in etl
    DataToCSV(df)
  File "/opt/airflow/dags/MySQL_to_CSV.py", line 66, in DataToCSV
    df.to_csv(mkdirPath+"/"+file_name,index=False)
NameError: name 'mkdirPath' is not defined
[2022-01-19 14:20:04,314] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-19 14:20:04,409] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-19 14:20:35,059] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv manual__2022-01-19T14:20:31.573029+00:00 [queued]>
[2022-01-19 14:20:35,113] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv manual__2022-01-19T14:20:31.573029+00:00 [queued]>
[2022-01-19 14:20:35,115] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 14:20:35,117] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-19 14:20:35,119] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 14:20:35,171] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): MySQLTOCsv> on 2022-01-19 14:20:31.573029+00:00
[2022-01-19 14:20:35,180] {standard_task_runner.py:52} INFO - Started process 7954 to run task
[2022-01-19 14:20:35,189] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MySQLTOCsv', 'MySQLTOCsv', 'manual__2022-01-19T14:20:31.573029+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py', '--cfg-path', '/tmp/tmpl06syik6', '--error-file', '/tmp/tmpbzhedp24']
[2022-01-19 14:20:35,191] {standard_task_runner.py:77} INFO - Job 14: Subtask MySQLTOCsv
[2022-01-19 14:20:35,316] {logging_mixin.py:109} INFO - Running <TaskInstance: MySQLTOCsv.MySQLTOCsv manual__2022-01-19T14:20:31.573029+00:00 [running]> on host 2d9e08f9455b
[2022-01-19 14:20:35,452] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MySQLTOCsv
AIRFLOW_CTX_TASK_ID=MySQLTOCsv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T14:20:31.573029+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-19T14:20:31.573029+00:00
[2022-01-19 14:20:35,499] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-19 14:20:35,504] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-19 14:20:35,506] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-19 14:20:35,508] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-19 14:20:35,509] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-19 14:20:35,511] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-19 14:20:35,513] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-19 14:20:35,514] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-19 14:20:35,550] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-19 14:20:35,552] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-19 14:20:35,554] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:20:35,555] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:20:35,557] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-19 14:20:35,558] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-19 14:20:35,559] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-19 14:20:35,561] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-19 14:20:35,562] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-19 14:20:35,564] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-19 14:20:35,566] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-19 14:20:35,568] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-19 14:20:35,570] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-19 14:20:35,572] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-19 14:20:35,573] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-19 14:20:35,575] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-19 14:20:35,576] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-19 14:20:35,578] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-19 14:20:35,580] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-19 14:20:35,581] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-19 14:20:35,583] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-19 14:20:35,584] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-19 14:20:35,586] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-19 14:20:35,587] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-19 14:20:35,589] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-19 14:20:35,590] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-19 14:20:35,592] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-19 14:20:35,593] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-19 14:20:35,595] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-19 14:20:35,597] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-19 14:20:35,598] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-19 14:20:35,600] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-19 14:20:35,602] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-19 14:20:35,603] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-19 14:20:35,605] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-19 14:20:35,608] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-19 14:20:35,609] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-19 14:20:35,610] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:20:35,612] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:20:35,614] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:20:35,616] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-19 14:20:35,617] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-19 14:20:35,619] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-19 14:20:35,621] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-19 14:20:35,622] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-19 14:20:35,624] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-19 14:20:35,625] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:20:35,627] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:20:35,628] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:20:35,630] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-19 14:20:35,632] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-19 14:20:35,633] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-19 14:20:35,635] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-19 14:20:35,636] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-19 14:20:35,637] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-19 14:20:35,639] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-19 14:20:35,640] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-19 14:20:35,641] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 79, in etl
    df = load()
[2022-01-19 14:20:35,643] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 70, in load
    cur = _get_MySQL_Connection()
[2022-01-19 14:20:35,644] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/.ipynb_checkpoints/MySQL_to_CSV-checkpoint.py", line 48, in _get_MySQL_Connection
    logging.info('DB Connect : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )
[2022-01-19 14:20:35,645] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-19 14:20:35,646] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-19 14:20:35,647] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-19 14:20:35,649] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-19 14:20:35,650] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-19 14:20:35,651] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-19 14:20:35,653] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-19 14:20:35,654] {logging_mixin.py:109} WARNING - Message: 'DB Connect : '
Arguments: ('2022.01.19.14.20',)
[2022-01-19 14:20:35,706] {python.py:152} INFO - Done. Returned value was: None
[2022-01-19 14:20:35,744] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=MySQLTOCsv, task_id=MySQLTOCsv, execution_date=20220119T142031, start_date=20220119T142035, end_date=20220119T142035
[2022-01-19 14:20:35,804] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-19 14:20:35,897] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-01-19 14:27:58,655] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv manual__2022-01-19T14:27:55.439393+00:00 [queued]>
[2022-01-19 14:27:58,713] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: MySQLTOCsv.MySQLTOCsv manual__2022-01-19T14:27:55.439393+00:00 [queued]>
[2022-01-19 14:27:58,715] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 14:27:58,717] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2022-01-19 14:27:58,719] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-01-19 14:27:58,767] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): MySQLTOCsv> on 2022-01-19 14:27:55.439393+00:00
[2022-01-19 14:27:58,775] {standard_task_runner.py:52} INFO - Started process 8335 to run task
[2022-01-19 14:27:58,784] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'MySQLTOCsv', 'MySQLTOCsv', 'manual__2022-01-19T14:27:55.439393+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/MySQL_to_CSV.py', '--cfg-path', '/tmp/tmp859aa95w', '--error-file', '/tmp/tmptdkvlcb1']
[2022-01-19 14:27:58,786] {standard_task_runner.py:77} INFO - Job 15: Subtask MySQLTOCsv
[2022-01-19 14:27:58,890] {logging_mixin.py:109} INFO - Running <TaskInstance: MySQLTOCsv.MySQLTOCsv manual__2022-01-19T14:27:55.439393+00:00 [running]> on host 2d9e08f9455b
[2022-01-19 14:27:59,027] {taskinstance.py:1414} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=MySQLTOCsv
AIRFLOW_CTX_TASK_ID=MySQLTOCsv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-19T14:27:55.439393+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-19T14:27:55.439393+00:00
[2022-01-19 14:27:59,073] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-19 14:27:59,078] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-19 14:27:59,080] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-19 14:27:59,081] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-19 14:27:59,082] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-19 14:27:59,083] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-19 14:27:59,085] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-19 14:27:59,086] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-19 14:27:59,117] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-19 14:27:59,119] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-19 14:27:59,121] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:27:59,122] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:27:59,124] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-19 14:27:59,126] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-19 14:27:59,127] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-19 14:27:59,129] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-19 14:27:59,131] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-19 14:27:59,132] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-19 14:27:59,134] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-19 14:27:59,136] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-19 14:27:59,137] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-19 14:27:59,139] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-19 14:27:59,140] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-19 14:27:59,141] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-19 14:27:59,143] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-19 14:27:59,144] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-19 14:27:59,145] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-19 14:27:59,146] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-19 14:27:59,147] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-19 14:27:59,149] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-19 14:27:59,150] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-19 14:27:59,152] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-19 14:27:59,154] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-19 14:27:59,155] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-19 14:27:59,157] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-19 14:27:59,158] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-19 14:27:59,159] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-19 14:27:59,160] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-19 14:27:59,162] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-19 14:27:59,163] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-19 14:27:59,165] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-19 14:27:59,166] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-19 14:27:59,167] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-19 14:27:59,168] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-19 14:27:59,169] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-19 14:27:59,171] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:27:59,172] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:27:59,173] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:27:59,175] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-19 14:27:59,177] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-19 14:27:59,178] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-19 14:27:59,179] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-19 14:27:59,180] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-19 14:27:59,181] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-19 14:27:59,183] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:27:59,184] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:27:59,185] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:27:59,186] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-19 14:27:59,188] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-19 14:27:59,189] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-19 14:27:59,191] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-19 14:27:59,192] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-19 14:27:59,193] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-19 14:27:59,194] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-19 14:27:59,195] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-19 14:27:59,197] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 80, in etl
    df = load()
[2022-01-19 14:27:59,198] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 71, in load
    cur = _get_MySQL_Connection()
[2022-01-19 14:27:59,200] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 48, in _get_MySQL_Connection
    logging.info('DB Connect : ',datetime.now().strftime('%Y.%m.%d.%H.%M') )
[2022-01-19 14:27:59,201] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-19 14:27:59,202] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-19 14:27:59,203] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-19 14:27:59,204] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-19 14:27:59,205] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-19 14:27:59,207] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-19 14:27:59,208] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-19 14:27:59,210] {logging_mixin.py:109} WARNING - Message: 'DB Connect : '
Arguments: ('2022.01.19.14.27',)
[2022-01-19 14:27:59,252] {logging_mixin.py:109} WARNING - --- Logging error ---
[2022-01-19 14:27:59,255] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-01-19 14:27:59,257] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
[2022-01-19 14:27:59,258] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
[2022-01-19 14:27:59,260] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
[2022-01-19 14:27:59,262] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
[2022-01-19 14:27:59,263] {logging_mixin.py:109} WARNING - TypeError: not all arguments converted during string formatting
[2022-01-19 14:27:59,265] {logging_mixin.py:109} WARNING - Call stack:
[2022-01-19 14:27:59,269] {logging_mixin.py:109} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2022-01-19 14:27:59,272] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/__main__.py", line 40, in main
    args.func(args)
[2022-01-19 14:27:59,273] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:27:59,274] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:27:59,275] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 188, in worker
    _run_worker(options=options, skip_serve_logs=skip_serve_logs)
[2022-01-19 14:27:59,277] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/celery_command.py", line 94, in _run_worker
    celery_app.worker_main(options)
[2022-01-19 14:27:59,278] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2022-01-19 14:27:59,279] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2022-01-19 14:27:59,281] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
[2022-01-19 14:27:59,282] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2022-01-19 14:27:59,283] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2022-01-19 14:27:59,284] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
[2022-01-19 14:27:59,285] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
[2022-01-19 14:27:59,287] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/base.py", line 133, in caller
    return f(ctx, *args, **kwargs)
[2022-01-19 14:27:59,288] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bin/worker.py", line 346, in worker
    worker.start()
[2022-01-19 14:27:59,289] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/worker/worker.py", line 203, in start
    self.blueprint.start(self)
[2022-01-19 14:27:59,291] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2022-01-19 14:27:59,292] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2022-01-19 14:27:59,293] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/base.py", line 129, in start
    self.on_start()
[2022-01-19 14:27:59,295] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/prefork.py", line 113, in on_start
    **self.options)
[2022-01-19 14:27:59,296] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 460, in __init__
    super().__init__(processes, *args, **kwargs)
[2022-01-19 14:27:59,297] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2022-01-19 14:27:59,298] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
    return super()._create_worker_process(i)
[2022-01-19 14:27:59,300] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2022-01-19 14:27:59,301] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 124, in start
    self._popen = self._Popen(self)
[2022-01-19 14:27:59,303] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/context.py", line 333, in _Popen
    return Popen(process_obj)
[2022-01-19 14:27:59,304] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 24, in __init__
    self._launch(process_obj)
[2022-01-19 14:27:59,305] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/popen_fork.py", line 79, in _launch
    code = process_obj._bootstrap()
[2022-01-19 14:27:59,306] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
[2022-01-19 14:27:59,307] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
[2022-01-19 14:27:59,308] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2022-01-19 14:27:59,309] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2022-01-19 14:27:59,310] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 647, in fast_trace_task
    uuid, args, kwargs, request,
[2022-01-19 14:27:59,311] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
    R = retval = fun(*args, **kwargs)
[2022-01-19 14:27:59,313] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
    return self.run(*args, **kwargs)
[2022-01-19 14:27:59,314] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 90, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2022-01-19 14:27:59,315] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/executors/celery_executor.py", line 121, in _execute_in_fork
    args.func(args)
[2022-01-19 14:27:59,316] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:27:59,318] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:27:59,319] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:27:59,321] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 105, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
[2022-01-19 14:27:59,322] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 163, in _run_task_by_local_task_job
    run_job.run()
[2022-01-19 14:27:59,323] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/base_job.py", line 245, in run
    self._execute()
[2022-01-19 14:27:59,325] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/jobs/local_task_job.py", line 103, in _execute
    self.task_runner.start()
[2022-01-19 14:27:59,326] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2022-01-19 14:27:59,327] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
[2022-01-19 14:27:59,328] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
[2022-01-19 14:27:59,329] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
[2022-01-19 14:27:59,331] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 292, in task_run
    _run_task_by_selected_method(args, dag, ti)
[2022-01-19 14:27:59,332] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
[2022-01-19 14:27:59,333] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
[2022-01-19 14:27:59,334] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
[2022-01-19 14:27:59,336] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1324, in _run_raw_task
    self._execute_task_with_callbacks(context)
[2022-01-19 14:27:59,337] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1443, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
[2022-01-19 14:27:59,338] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py", line 1499, in _execute_task
    result = execute_callable(context=context)
[2022-01-19 14:27:59,339] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 151, in execute
    return_value = self.execute_callable()
[2022-01-19 14:27:59,340] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/operators/python.py", line 162, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2022-01-19 14:27:59,342] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 81, in etl
    DataToCSV(df)
[2022-01-19 14:27:59,343] {logging_mixin.py:109} WARNING -   File "/opt/***/dags/MySQL_to_CSV.py", line 69, in DataToCSV
    logging.info('File Created: ', output_file)
[2022-01-19 14:27:59,344] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1992, in info
    root.info(msg, *args, **kwargs)
[2022-01-19 14:27:59,345] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1378, in info
    self._log(INFO, msg, args, **kwargs)
[2022-01-19 14:27:59,346] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
[2022-01-19 14:27:59,347] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
[2022-01-19 14:27:59,348] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
    hdlr.handle(record)
[2022-01-19 14:27:59,350] {logging_mixin.py:109} WARNING -   File "/usr/local/lib/python3.7/logging/__init__.py", line 894, in handle
    self.emit(record)
[2022-01-19 14:27:59,351] {logging_mixin.py:109} WARNING -   File "/home/***/.local/lib/python3.7/site-packages/***/utils/log/file_task_handler.py", line 66, in emit
    self.handler.emit(record)
[2022-01-19 14:27:59,353] {logging_mixin.py:109} WARNING - Message: 'File Created: '
Arguments: ('/opt/***/data/mysqlData/2022.01.19_14.27_output.csv',)
[2022-01-19 14:27:59,354] {python.py:152} INFO - Done. Returned value was: None
[2022-01-19 14:27:59,387] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=MySQLTOCsv, task_id=MySQLTOCsv, execution_date=20220119T142755, start_date=20220119T142758, end_date=20220119T142759
[2022-01-19 14:27:59,480] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-01-19 14:27:59,596] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
